[package]
name = "coopshield"
version = "1.0.0"
description = "Enterprise Backup para o Sicoob Primavera"
authors = ["Douglas Bini - Sicoob Primavera"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
lazy_static = "1.5.0"
parking_lot = "0.12.5"
sha2 = "0.10"
aes-gcm = "0.10"
rand = "0.8"
walkdir = "2.5"
tauri-plugin-dialog = "2"
rfd = "0.14"
hex = "0.4"
chrono = "0.4"
dirs = "5.0"
base64 = "0.22"
tauri-plugin-notification = "2.5.0"
zstd = "0.13"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.21.0"
tokio = { version = "1.36", features = ["full"] }
mac_address = "1.2.0"
hostname = "0.4.2"
reqwest = "0.13.5"
